# Generated by Django 5.1.2 on 2024-10-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram Chat ID для уведомлений', max_length=100, null=True),
        ),
    ]
