# Generated by Django 5.1.2 on 2024-10-13 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('periodicity', models.PositiveIntegerField(help_text='Периодичность выполнения привычки в днях.')),
                ('execution_time', models.PositiveIntegerField(help_text='Время выполнения привычки в секундах.')),
                ('reward', models.CharField(blank=True, help_text='Вознаграждение за выполнение привычки', max_length=255, null=True)),
                ('is_pleasant', models.BooleanField(default=False, help_text='Является ли привычка приятной')),
                ('is_public', models.BooleanField(default=False, help_text='Является ли привычка публичной')),
                ('linked_habit', models.ForeignKey(blank=True, help_text='Связанная привычка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_habits', to='habits.userhabit')),
            ],
        ),
    ]
